### ISSUE TITLE
VS benchmark data

### ISSUE THREAD

**Issue by HBioquant** [CAODH/EquiScore#4]
你好~想请问能否公开一下在DUDE和DEKOIS2两个基准数据集上预印本中其他对接学习方法的各项虚拟筛选指标数据(精确到靶标层面)呢？比如，PIGNet和Tankbind等。期待您的答复，感激不尽。

**Comment by CAODH** [comment]
当然可以呀,你可以提供一下邮箱，我整理发给你，或者等几天我上传到数据仓库。我会第一时间通知你。

**Comment by HBioquant** [comment]
> 当然可以呀,你可以提供一下邮箱，我整理发给你，或者等几天我上传到数据仓库。我会第一时间通知你。

十分感谢，那我等你把数据上传到仓库啦~

**Comment by CAODH** [comment]
> > 当然可以呀,你可以提供一下邮箱，我整理发给你，或者等几天我上传到数据仓库。我会第一时间通知你。
> 
> 十分感谢，那我等你把数据上传到仓库啦~

okk

**Comment by CAODH** [comment]
> > > 当然可以呀,你可以提供一下邮箱，我整理发给你，或者等几天我上传到数据仓库。我会第一时间通知你。
> > 
> > 
> > 十分感谢，那我等你把数据上传到仓库啦~
> 
> okk
你好，我已经在这个链接（https://zenodo.org/records/10416719）上传了你需要的数据，如果有问题，请与我联系。感谢你的关注。

**Comment by HBioquant** [comment]
> > > > 当然可以呀,你可以提供一下邮箱，我整理发给你，或者等几天我上传到数据仓库。我会第一时间通知你。
> > > 
> > > 
> > > 十分感谢，那我等你把数据上传到仓库啦~
> > 
> > 
> > okk
> > 你好，我已经在这个链接 https://zenodo.org/records/10416719
> > 上传了你需要的数据，如果有问题，请与我联系。感谢你的关注。

收到，十分感谢~
